- hosts: ec2_instance
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: devops-blog-image:latest  # 
        source: pull

    - name: Run Docker container
      docker_container:
        name: your_container_name
        image: devops-blog-image:latest  # 
        state: started
        ports:
          - "8080:80"